# Generated by Django 4.2.5 on 2023-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fixed',
            new_name='is_fixed',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.IntegerField(default=0),
        ),
    ]
