# Generated by Django 4.2.5 on 2023-09-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_remove_order_profile_order_profile_id_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
