# Generated by Django 4.2.5 on 2023-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_rename_fixed_order_is_fixed_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile_id',
            field=models.IntegerField(default=1),
        ),
    ]
