# Generated by Django 4.2.5 on 2023-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_remove_order_profile_order_profile_id_green'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_table',
            field=models.IntegerField(null=True),
        ),
    ]
