# Generated by Django 4.2.5 on 2023-09-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_order_new_table_blue'),
    ]

    operations = [
    ]
