# Generated by Django 4.2.5 on 2023-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='new_field',
            field=models.BooleanField(default=True),
        ),
    ]
