# Generated by Django 4.2.5 on 2023-09-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0003_remove_user_is_staff_address_new_field_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
