# Generated by Django 4.2.5 on 2023-09-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0004_remove_address_new_field_user_is_staff_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='new_field',
        ),
    ]
